// frontend/vuejs/src/components/Department/EditDepartment.vue
<template>
  <div class="text-start">
    <div class="mb-3">
      <label for="department_name_input" class="form-label">
        Department Name
      </label>
      <input
        id="department_name_input"
        type="text"
        class="form-control"
        v-model="DepartmentName"
        placeholder="Enter Department Name"
      />
    </div>

    <div class="d-flex justify-content-end">
      <button
        class="btn btn-primary"
        v-if="Department.DepartmentId == 0"
        @click="addDepartment()"
      >
        Add Department
      </button>
      <button
        class="btn btn-primary"
        @click="editDepartment()"
        v-else
      >
        Update Department
      </button>
    </div>
  </div>
</template>

<script>
import http from '../../repositories/Repository.js';

export default {
  name: 'EditDepartment',

  props: {
    Department: {
      type: Object,
      required: true,
    },
  },

  data() {
    return {
      DepartmentId: '',
      DepartmentName: '',
    };
  },

  mounted() {
    this.DepartmentId = this.Department.DepartmentId;
    this.DepartmentName = this.Department.DepartmentName;
  },

  methods: {
    addDepartment() {
      const department = { DepartmentName: this.DepartmentName };
      http
        .addDepartment(department)
        .then(({ data }) => {
          console.log(data);
          this.$emit('departmentUpdated');
        });
    },

    editDepartment() {
      const department = {
        DepartmentId: this.DepartmentId,
        DepartmentName: this.DepartmentName
      };

      http
        .updateDepartment(department)
        .then(({ data }) => {
          console.log(data);
          this.$emit('departmentUpdated');
        });
    },
  },
}
</script>

<style>

</style>

// frontend/react-app/src/components/Department/EditDepartment/EditDepartment.js
import React from "react";
import http from "../../../repositories/Repository.js";

class EditDepartment extends React.Component {

    constructor(props) {
      super(props);
      this.state = {
        DepartmentId: props.Department.DepartmentId,
        DepartmentName: props.Department.DepartmentName
      };
    }

    changeName = (event) => {
      this.setState({ DepartmentName: event.target.value });
    };

    addDepartment = () => {
      const department = { DepartmentName: this.state.DepartmentName };
      http.addDepartment(department)
        .then(({ data }) => {
          console.log(data);
          this.props.departmentUpdated();
        });
    };

    editDepartment = () => {
      const department = this.state;
      http.updateDepartment(department)
        .then(({ data }) => {
          console.log(data);
          this.props.departmentUpdated();
        });
    }

    render() {
      const { DepartmentId, DepartmentName } = this.state;

      const ShowButton = (props) => {
        const { DepartmentId } = props;
        if (DepartmentId === 0 || DepartmentId === '0') {
          return (
            <button className="btn btn-primary" onClick={this.addDepartment}>
              Add Department
            </button>
          );
        }

        return (
          <button className="btn btn-primary" onClick={this.editDepartment}>
            Edit Department
          </button>
        );
      };

      return (
          <div>
            <div className="mb-3">
              <label htmlFor="department_name_input" className="form-label">
                Department Name
              </label>
              <input
                id="department_name_input"
                type="text"
                className="form-control"
                value={DepartmentName}
                onChange={this.changeName}
                placeholder="Enter Department Name"
              />
            </div>

            <div className="d-flex justify-content-end">
              <ShowButton DepartmentId={DepartmentId} />
            </div>
          </div>
    );
  }
}

export default EditDepartment;
