// frontend/vuejs/src/components/Department/ShowDepartment.vue
<template>
  <div>
    <!-- Button trigger modal -->
    <div class="d-flex justify-content-end">
      <button
        type="button"
        class="btn btn-primary mt-2 mb-2"
        data-bs-toggle="modal"
        data-bs-target="#departmentModal"
        @click="add()"
      >
        Create new Department
      </button>
    </div>

    <!-- Modal -->
    <div
      class="modal fade"
      id="departmentModal"
      tabindex="-1"
      aria-labelledby="DepartmentLabel"
      aria-hidden="true"
      data-bs-backdrop="static"
      data-bs-keyboard="false"
    >
      <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="DepartmentLabel">
              {{ ModalTitle }}
            </h5>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
              @click="closeModal()"
              id="closeButton"
            ></button>
          </div>
          <div class="modal-body">
            <EditDepartment
              :Department="Department"
              @departmentUpdated="listUpdated()"
              v-if="ActivateEditComponent"
            />
          </div>
        </div>
      </div>
    </div>

    <table class="table table-striped">
      <thead>
        <tr>
          <th class="text-center">ID</th>
          <th class="text-start">Department Name</th>
          <th class="text-end">Options</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="department in DepartmentList"
          :key="department.DepartmentId"
        >
          <td class="small text-muted text-center">
            <i>#{{ department.DepartmentId }}</i>
          </td>
          <td class="text-start">
            {{ department.DepartmentName }}
          </td>
          <td class="text-end">
            <button
              type="button"
              class="btn btn-sm btn-light mx-1"
              data-bs-toggle="modal"
              data-bs-target="#departmentModal"
              @click="update(department)"
            >
              Edit
            </button>
            <button
              type="button"
              class="btn btn-sm btn-light"
              @click="remove(department.DepartmentId)"
            >
              Delete
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
import http from '../../repositories/Repository.js';
import EditDepartment from './EditDepartment.vue';

export default {
  name: 'ShowDepartment',

  components: {
    EditDepartment,
  },

  data() {
    return {
      ModalTitle: '',
      Department: null,
      DepartmentList: [],
      ActivateEditComponent: false,
    };
  },

  mounted() {
    this.refreshDepartmentList();
  },

  methods: {
    add() {
      this.Department = {
        DepartmentId: 0,
        DepartmentName: ''
      };

      this.ModalTitle = 'Add Department';
      this.ActivateEditComponent = true;
    },

    update(department) {
      this.Department = department;
      this.ModalTitle = `Edit Department #${department.DepartmentId}`;
      this.ActivateEditComponent = true;
    },

    closeModal() {
      document.getElementById('closeButton')?.click();
      this.ModalTitle = '';
      this.ActivateEditComponent = false;
    },

    remove(departmentId) {
      http
        .deleteDepartment(departmentId)
        .then(({ data }) => {
          console.log(data);
          this.refreshDepartmentList();
        });
    },

    listUpdated() {
      this.closeModal();
      this.refreshDepartmentList();
    },

    refreshDepartmentList() {
      http
        .getDepartmentList()
        .then(({ data }) => {
          this.DepartmentList = data;
        });
    },
  },
};
</script>

<style>

</style>

// frontend/react-app/src/components/Department/ShowDepartment/ShowDepartment.js
import React from "react";
import http from "../../../repositories/Repository.js";

import EditDepartment from '../EditDepartment/EditDepartment.js';

class ShowDepartment extends React.Component {

    constructor() {
      super();
      this.state = {
        DepartmentList: [],
        ModalTitle: '',
        ActivateEditComponent: false,
        Department: null
      };
    }

    componentDidMount() {
      this.refreshDepartmentList();
    }

    add = () => {
      this.setState({
        ModalTitle: 'Add Department',
        ActivateEditComponent: true,
        Department: {
          DepartmentId: 0,
          DepartmentName: ''
        },
      });
    }

    update = (department) => {
      this.setState({
        Department: department,
        ModalTitle: `Edit Department #${department.DepartmentId}`,
        ActivateEditComponent: true,
      });
    }

    closeModal = () => {
      document.getElementById('closeButton')?.click();
      this.setState({
        ModalTitle: '',
        ActivateEditComponent: false,
      });
    }

    listUpdated = () => {
      this.closeModal();
      this.refreshDepartmentList();
    }

    remove = (DepartmentId) => {
      http.deleteDepartment(DepartmentId)
        .then(({ data }) => {
          console.log(data);
          this.refreshDepartmentList();
        });
    }

    refreshDepartmentList = () => {
      http.getDepartmentList()
        .then(({ data }) => {
          this.setState({ DepartmentList: data });
        });
    }

    render() {
      const { DepartmentList, ModalTitle, Department } = this.state;

      const renderTr = (department) => {
        return (
          <tr key={ department.DepartmentId }>
            <td className="small text-muted text-center">
              <i>#{ department.DepartmentId }</i>
            </td>
            <td className="text-start">{ department.DepartmentName }</td>
            <td className="text-end">
              <button
                type="button"
                className="btn btn-sm btn-light mx-1"
                data-bs-toggle="modal"
                data-bs-target="#departmentModal"
                onClick={() => { this.update(department) }}
              >
                Edit
              </button>
              <button
                type="button"
                className="btn btn-sm btn-light"
                onClick={() => { this.remove(department.DepartmentId) }}
              >
                Delete
              </button>
            </td>
          </tr>
        );
      };

      const EditDepartmentComponent = (props) => {
        if (props.Department) {
          return (
            <EditDepartment
              Department={props.Department}
              departmentUpdated={this.listUpdated}
            />
          );
        }
        return '';
      };

      return (
      <div>
        <div className="d-flex justify-content-end">
          <button
            type="button"
            className="btn btn-primary mt-2 mb-2"
            data-bs-toggle="modal"
            data-bs-target="#departmentModal"
            onClick={this.add}
          >
            Create new Department
          </button>
        </div>

        <div
          className="modal fade"
          id="departmentModal"
          tabIndex="-1"
          aria-labelledby="DepartmentLabel"
          aria-hidden="true"
          data-bs-backdrop="static"
          data-bs-keyboard="false"
        >
          <div className="modal-dialog modal-xl">
            <div className="modal-content">
              <div className="modal-header">
                <h5 className="modal-title" id="DepartmentLabel">
                  { ModalTitle }
                </h5>
                <button
                  type="button"
                  className="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                  onClick={this.closeModal}
                  id="closeButton"
                ></button>
              </div>
              <div className="modal-body text-start">
                <EditDepartmentComponent Department={Department} />
              </div>
            </div>
          </div>
        </div>

        <table className="table table-striped">
          <thead>
            <tr>
              <th className="text-center">ID</th>
              <th className="text-start">Department Name</th>
              <th className="text-end">Options</th>
            </tr>
          </thead>
          <tbody>
            { DepartmentList.map(renderTr) }
          </tbody>
        </table>
      </div>
    );
  }
}

export default ShowDepartment;
